### ISSUE TITLE
On the dataset view page, the feedback table of errors reverts to page 1 each time you switch back to the webpage

### ISSUE THREAD

**Issue by emmajclegg** [IATI/validator-web#984]
(similar to #887, and raised by YI)

**Brief Description**
On the dataset view page, which lists the validation errors in a reporting organisation's dataset, (example: https://dev-validator.iatistandard.org/report/worldbank-af), the feedback table is sorted by Validation status and paginated.

If I navigate to view later pages of the table...

<img width="1092" height="800" alt="Image" src="https://github.com/user-attachments/assets/4b9259a7-0c0b-4d57-80fb-3f68068c12e7" />

....then switch away from the browser and come back, or switch browser tab and then come back, the sort order reverts to display page 1 of the table again.

<img width="1085" height="778" alt="Image" src="https://github.com/user-attachments/assets/59aca9cb-a228-4118-bc98-ffb46f0a683e" />

**Severity**
Medium (it's very annoying when trying to compare pages of results)

**Comment by simon-20** [comment]
I fixed a related issue back in Sept 2024, where the filtering was being lost when navigating through the pages: https://github.com/IATI/validator-web/pull/747/files.

**Comment by emmajclegg** [comment]
@simon-20 - thanks for having an initial look.

This sounded like it was causing grief to organisations that need to systematically troubleshoot validation errors, particularly on behalf of other organisations.

Not urgent, but if it's something we can fix in the next month or so, that would be ideal.

**Comment by simon-20** [comment]
@emmajclegg Have pushed a fix for this in the PR mentioned above, and will release to dev where you can do some testing once it's been reviewed.

**Comment by emmajclegg** [comment]
@simon-20 - can I check where we got to on this?

I assumed a fix had been pushed to production because the issue was closed, but the problem remains - e.g. https://validator.iatistandard.org/report/oxfamgb-289  (pagination of feedback table resets every time you leave the page)

Reopening the GitHub issue for now.

**Comment by simon-20** [comment]
@emmajclegg It's on dev: https://dev-validator.iatistandard.org/report/oxfamgb-289

If you can confirm this is working as expected, I will draw up a PR to release this.

**Comment by emmajclegg** [comment]
Thanks @simon-20 - I hadn't realised.

I've tested this on the dev site and all looks to be working as expected

**Comment by simon-20** [comment]
I've just released this to production and all seems to be working well, so closing now.
